ENV_EXAMPLE = """
# Database Configuration
DATABASE_URL=postgresql+psycopg://user:password@localhost:5432/{db_name}

# Security
JWT_SECRET_KEY={jwt_secret}

# API Configuration
VITE_API_URL=http://localhost:8000
"""

GITIGNORE = """
# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Node
node_modules/
dist/
build/
npm-debug.log
yarn-error.log

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# OS
.DS_Store
Thumbs.db
"""

README_MD = """
# {app_name}

This project was automatically generated by the AI App Compiler.

## Overview

A modern web application built with:
- **Frontend**: React (Vite), TailwindCSS, Zustand
- **Backend**: FastAPI, SQLAlchemy, PostgreSQL
- **DevOps**: Docker & Docker Compose

## Quick Start (Docker)

The easiest way to run the application is using Docker.

```bash
docker-compose up --build
```

The application will be available at:
- Frontend: http://localhost:3000
- Backend API Docs: http://localhost:8000/docs

## Manual Setup

### Backend

1. Navigate to the `backend` directory.
2. Create a virtual environment: `python -m venv venv`
3. Activate it and install dependencies: `pip install -r requirements.txt`
4. Copy `.env.example` to `.env` and configure your database.
5. Run the server: `uvicorn main:app --reload`

### Frontend

1. Navigate to the `frontend` directory.
2. Install dependencies: `npm install`
3. Start the dev server: `npm run dev`

"""
